# Tested on AWS (m6g.large) ARM Graviton2 (Neoverse-N1), Architecture: aarch64
# Tested on AWS (a1.large)  ARM (Cortex-A72), Architecture: aarch64
FROM arm64v8/openjdk:11.0.7-jre-slim-buster
COPY iam-service-1.0.0-SNAPSHOT.jar /iam-service-1.0.0-SNAPSHOT.jar
ENTRYPOINT ["java", "-Xms32m", "-Xms128m", "-jar","/iam-service-1.0.0-SNAPSHOT.jar"]
